# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PyQt5.Qt import *
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1067, 852)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.img_show = ImageShow(self.scrollArea)
        self.img_show.setEnabled(True)
        self.img_show.setGeometry(QtCore.QRect(0, 0, 521, 771))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_show.sizePolicy().hasHeightForWidth())
        self.img_show.setSizePolicy(sizePolicy)
        self.img_show.setObjectName("img_show")
        self.scrollArea.setWidget(self.img_show)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setAlignment(Qt.AlignCenter)
        self.verticalLayout.addWidget(self.scrollArea)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.savebtn = QtWidgets.QPushButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.savebtn.setIcon(icon)
        self.savebtn.setObjectName("savebtn")
        self.horizontalLayout.addWidget(self.savebtn)
        self.previousbtn = QtWidgets.QPushButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/leftarrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previousbtn.setIcon(icon1)
        self.previousbtn.setObjectName("previousbtn")
        self.horizontalLayout.addWidget(self.previousbtn)
        self.nextbtn = QtWidgets.QPushButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("res/rightarrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextbtn.setIcon(icon2)
        self.nextbtn.setObjectName("nextbtn")
        self.horizontalLayout.addWidget(self.nextbtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.zoom_inbtn = QtWidgets.QPushButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("res/zoomin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoom_inbtn.setIcon(icon3)
        self.zoom_inbtn.setObjectName("zoom_inbtn")
        self.horizontalLayout_4.addWidget(self.zoom_inbtn)
        self.zoom_out_btn = QtWidgets.QPushButton(self.centralwidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("res/zoom-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoom_out_btn.setIcon(icon4)
        self.zoom_out_btn.setObjectName("zoom_out_btn")
        self.horizontalLayout_4.addWidget(self.zoom_out_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)

        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.markinbtn = QtWidgets.QPushButton(self.centralwidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("res/marker.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.markinbtn.setIcon(icon5)
        self.markinbtn.setObjectName("markinbtn")
        self.horizontalLayout_6.addWidget(self.markinbtn)

        self.exit_mark_btn = QtWidgets.QPushButton(self.centralwidget)  # 退出打标按钮
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("res/drag.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_mark_btn.setIcon(icon6)
        self.exit_mark_btn.setObjectName("exit_mark_btn")
        self.horizontalLayout_6.addWidget(self.exit_mark_btn)

        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.opendirbtn = QtWidgets.QPushButton(self.centralwidget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("res/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.opendirbtn.setIcon(icon7)
        self.opendirbtn.setObjectName("opendirbtn")
        self.horizontalLayout_2.addWidget(self.opendirbtn)
        self.setdefaultdirbtn = QtWidgets.QPushButton(self.centralwidget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("res/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setdefaultdirbtn.setIcon(icon8)
        self.setdefaultdirbtn.setObjectName("setdefaultdirbtn")
        self.horizontalLayout_2.addWidget(self.setdefaultdirbtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1067, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "图片打标工具"))
        self.img_show.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.savebtn.setText(_translate("MainWindow", "保存"))
        self.savebtn.setShortcut(_translate("MainWindow", "S"))
        self.previousbtn.setText(_translate("MainWindow", "上一张"))
        self.previousbtn.setShortcut(_translate("MainWindow", "W"))
        self.nextbtn.setText(_translate("MainWindow", "下一张"))
        self.nextbtn.setShortcut(_translate("MainWindow", "E"))
        self.zoom_inbtn.setText(_translate("MainWindow", "放大"))
        self.zoom_inbtn.setShortcut(_translate("MainWindow", "Ctrl+="))
        self.zoom_out_btn.setText(_translate("MainWindow", "缩小"))
        self.zoom_out_btn.setShortcut(_translate("MainWindow", "Ctrl+-"))
        self.markinbtn.setText(_translate("MainWindow", "打标"))
        self.markinbtn.setShortcut(_translate("MainWindow", "Q"))

        self.exit_mark_btn.setText(_translate("MainWindow", "退出打标模式"))
        self.exit_mark_btn.setShortcut(_translate("MainWindow", "Esc"))

        self.opendirbtn.setText(_translate("MainWindow", "打开文件夹"))
        self.opendirbtn.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.setdefaultdirbtn.setText(_translate("MainWindow", "设置保存默认文件夹"))
        self.setdefaultdirbtn.setShortcut(_translate("MainWindow", "Ctrl+K"))
from model import ImageShow
